/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesalquerias.word;

import javax.swing.JList;

/**
 * @author andreu
 */
public class Estilos extends javax.swing.JPanel {

    public Estilos() {
        initComponents();
    }
    
    /**
     * 
     * @return lista donde estan los estilos
     */
    public JList<String> getJList() {
        return jList1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(200, 120));
        setPreferredSize(new java.awt.Dimension(300, 120));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><p style=\"font-family:'Courier New'\">Actual</p><p></p><p>Actual</p></html>", "<html><p>Estilo 1</p><p></p><p>Subtitulo 1</p></html>", "<html><p>Estilo 1</p><p></p><p>Subtitulo 2</p></html>", "<html><p>Estilo 1</p><p></p><p>Subtitulo 3</p></html>", "<html><p>Estilo 2</p><p></p><p>Subtitulo 1</p></html>", "<html><p>Estilo 2</p><p></p><p>Subtitulo 2</p></html>", "<html><p>Estilo 2</p><p></p><p>Subtitulo 3</p></html>", "<html><p>Estilo 3</p><p></p><p>Subtitulo 1</p></html>", "<html><p>Estilo 3</p><p></p><p>Subtitulo 2</p></html>", "<html><p>Estilo 3</p><p></p><p>Subtitulo 3</p></html>", "<html><p>Estilo 4</p><p></p><p>Subtitulo 1</p></html>", "<html><p>Estilo 4</p><p></p><p>Subtitulo 2</p></html>" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jList1.setMinimumSize(new java.awt.Dimension(400, 120));
        jList1.setVisibleRowCount(2);
        jScrollPane2.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(249, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estilos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jLabel1, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jSeparator1, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
